// ============================================
// questions.js — 40-question privacy assessment
// 10 categories, 4 questions each
// ============================================

const CATEGORIES = {
  A: { id:'A', name:'Profile Visibility',       weight:12, color:'#a78bfa' },
  B: { id:'B', name:'Personal Information',     weight:12, color:'#00cfff' },
  C: { id:'C', name:'Location Privacy',         weight:12, color:'#ff9100' },
  D: { id:'D', name:'Posts & Content',          weight:10, color:'#5b8fff' },
  E: { id:'E', name:'Friends & Followers',      weight:8,  color:'#f472b6' },
  F: { id:'F', name:'Tagging & Mentions',       weight:8,  color:'#ffd600' },
  G: { id:'G', name:'Authentication & Security',weight:14, color:'#00e676' },
  H: { id:'H', name:'Third-Party Apps',         weight:8,  color:'#ff1744' },
  I: { id:'I', name:'Messaging & Social Eng',   weight:8,  color:'#f5c518' },
  J: { id:'J', name:'Digital Footprint',        weight:8,  color:'#a3e635' },
}

const QUESTIONS = [
  // CATEGORY A — Profile Visibility
  { id:'A1', cat:'A', text:'Is your social media profile set to Public (visible to everyone)?',
    options:['Public','Friends Only','Private','Not Sure'],
    risk:   [1.0, 0.4, 0.0, 0.7],
    tip:'Set your profile to Friends Only or Private to limit exposure to strangers.' },
  { id:'A2', cat:'A', text:'Does your profile photo clearly show your face?',
    options:['Yes','No','Sometimes','Not Sure'],
    risk:   [0.8, 0.0, 0.4, 0.5],
    tip:'Using a non-identifying profile photo reduces facial recognition and impersonation risk.' },
  { id:'A3', cat:'A', text:'Is your full real name displayed on your profile?',
    options:['Yes','No','Partial','Not Sure'],
    risk:   [0.9, 0.0, 0.3, 0.5],
    tip:'Consider using a username or first name only to reduce doxxing risk.' },
  { id:'A4', cat:'A', text:'Can anyone search for your profile using your email or phone number?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [1.0, 0.0, 0.6, 0.7],
    tip:'Disable search by email and phone in your privacy settings.' },

  // CATEGORY B — Personal Information
  { id:'B1', cat:'B', text:'Is your phone number visible on your profile?',
    options:['Yes – Public','Friends Only','No','Not Sure'],
    risk:   [1.0, 0.4, 0.0, 0.6],
    tip:'Never expose your phone number publicly — it enables SIM swapping and harassment.' },
  { id:'B2', cat:'B', text:'Is your full date of birth (day/month/year) publicly visible?',
    options:['Yes – Full','Month & Day Only','No','Not Sure'],
    risk:   [1.0, 0.5, 0.0, 0.6],
    tip:'Full birth dates are used for identity verification attacks. Hide the year at minimum.' },
  { id:'B3', cat:'B', text:'Is your personal email address visible on your profile?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [1.0, 0.0, 0.6, 0.7],
    tip:'Keep your personal email private. Use a dedicated contact form instead.' },
  { id:'B4', cat:'B', text:'Is your workplace or school publicly listed on your profile?',
    options:['Yes – Both','One of them','No','Not Sure'],
    risk:   [0.9, 0.5, 0.0, 0.5],
    tip:'Workplace exposure enables targeted spear-phishing and social engineering attacks.' },

  // CATEGORY C — Location Privacy
  { id:'C1', cat:'C', text:'Do you share your real-time or current location in posts?',
    options:['Yes – Often','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Real-time location sharing enables physical tracking. Disable location on social apps.' },
  { id:'C2', cat:'C', text:'Do you post travel plans before or during your trip?',
    options:['Yes – Always','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Posting travel plans publicly signals an empty home — a burglary risk.' },
  { id:'C3', cat:'C', text:'Is your home city or neighborhood publicly visible?',
    options:['Yes – Specific','City Only','No','Not Sure'],
    risk:   [1.0, 0.4, 0.0, 0.5],
    tip:'Limit location info to country or region. Specific neighborhoods enable physical risk.' },
  { id:'C4', cat:'C', text:'Do your photos contain embedded GPS metadata (EXIF data)?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [0.8, 0.0, 0.7, 0.7],
    tip:'Strip EXIF metadata from photos before posting. Use tools like ExifTool or Photo Privacy.' },

  // CATEGORY D — Posts & Content
  { id:'D1', cat:'D', text:'Are your social media posts visible to the public by default?',
    options:['Yes – All Public','Mixed','Friends Only','Private'],
    risk:   [1.0, 0.5, 0.2, 0.0],
    tip:'Change your default post audience to Friends or a custom group.' },
  { id:'D2', cat:'D', text:'Do you share personal opinions, political views, or religious beliefs publicly?',
    options:['Yes – Frequently','Sometimes','Rarely','Never'],
    risk:   [0.8, 0.5, 0.2, 0.0],
    tip:'Public opinions can be used for profiling, targeted harassment, or discrimination.' },
  { id:'D3', cat:'D', text:'Have you ever reviewed and cleaned up your old posts?',
    options:['Never','Rarely','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.7, 0.4, 0.0],
    tip:'Old posts may expose information you no longer want public. Use archive or delete tools.' },
  { id:'D4', cat:'D', text:'Do you post photos of children, family members, or friends without their consent?',
    options:['Yes – Often','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Always get consent before sharing others photos. Especially protect children online.' },

  // CATEGORY E — Friends & Followers
  { id:'E1', cat:'E', text:'Do you accept friend/follow requests from people you do not know?',
    options:['Yes – Always','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Unknown connections can be fake accounts used for surveillance or social engineering.' },
  { id:'E2', cat:'E', text:'Is your friends/followers list publicly visible?',
    options:['Yes – Public','Friends Only','No','Not Sure'],
    risk:   [0.9, 0.3, 0.0, 0.5],
    tip:'A public friends list enables network mapping and targeted social engineering.' },
  { id:'E3', cat:'E', text:'Do you have a large number of unknown followers (500+)?',
    options:['Yes','No','Not Sure','I don\'t check'],
    risk:   [0.8, 0.0, 0.5, 0.6],
    tip:'Regularly audit your followers list and remove unknown or suspicious accounts.' },
  { id:'E4', cat:'E', text:'Do you review who can see your friend list and connections?',
    options:['Never','Rarely','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.7, 0.3, 0.0],
    tip:'Restrict friend list visibility to Friends Only in your privacy settings.' },

  // CATEGORY F — Tagging & Mentions
  { id:'F1', cat:'F', text:'Can anyone tag you in photos or posts without your approval?',
    options:['Yes – Anyone','Friends Only','No – I Approve All','Not Sure'],
    risk:   [1.0, 0.4, 0.0, 0.6],
    tip:'Enable tag review so you approve all tags before they appear on your profile.' },
  { id:'F2', cat:'F', text:'Do tagged posts from others appear on your profile automatically?',
    options:['Yes – Always','Sometimes','No','Not Sure'],
    risk:   [0.9, 0.5, 0.0, 0.6],
    tip:'Disable automatic tag publishing. Review tags manually before they go live.' },
  { id:'F3', cat:'F', text:'Can you be mentioned or tagged by people you don\'t follow?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [0.8, 0.0, 0.5, 0.6],
    tip:'Restrict mentions and tags to Friends or followers only.' },
  { id:'F4', cat:'F', text:'Do you check your tag settings regularly?',
    options:['Never','Rarely','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.7, 0.3, 0.0],
    tip:'Review tagging permissions in Settings > Privacy every few months.' },

  // CATEGORY G — Authentication & Security
  { id:'G1', cat:'G', text:'Do you use Multi-Factor Authentication (MFA) on your social accounts?',
    options:['No','On Some','On All','Not Sure What MFA Is'],
    risk:   [1.0, 0.5, 0.0, 0.9],
    tip:'Enable MFA on ALL social accounts immediately. Use an authenticator app, not SMS.' },
  { id:'G2', cat:'G', text:'Do you reuse the same password across multiple social media platforms?',
    options:['Yes – Same Password','Similar Passwords','No – All Different','I Use a Password Manager'],
    risk:   [1.0, 0.7, 0.1, 0.0],
    tip:'Use a password manager and unique passwords for every account.' },
  { id:'G3', cat:'G', text:'Have you received login alerts for your social media accounts?',
    options:['Yes – Ignored','Yes – Acted On','No Alerts Set Up','Not Sure'],
    risk:   [1.0, 0.1, 0.8, 0.7],
    tip:'Enable login alerts. Any unrecognized login should trigger an immediate password change.' },
  { id:'G4', cat:'G', text:'When did you last change your social media passwords?',
    options:['Never','Over 1 Year Ago','6–12 Months Ago','Recently'],
    risk:   [1.0, 0.8, 0.4, 0.0],
    tip:'Change passwords every 6 months and immediately after any suspected breach.' },

  // CATEGORY H — Third-Party Apps
  { id:'H1', cat:'H', text:'Do you have third-party apps connected to your social accounts?',
    options:['Yes – Many','A Few','No','Not Sure'],
    risk:   [1.0, 0.5, 0.0, 0.7],
    tip:'Revoke access to apps you no longer use. Each app is a potential data breach vector.' },
  { id:'H2', cat:'H', text:'Do you use "Login with Facebook/Google/Twitter" for other websites?',
    options:['Yes – Often','Sometimes','Rarely','Never'],
    risk:   [0.8, 0.5, 0.2, 0.0],
    tip:'Social login shares your profile data with third parties. Use email login when possible.' },
  { id:'H3', cat:'H', text:'Have you ever reviewed what permissions third-party apps have?',
    options:['Never','Rarely','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.7, 0.3, 0.0],
    tip:'Go to Settings > Apps and review permissions. Remove any that seem excessive.' },
  { id:'H4', cat:'H', text:'Do you take quizzes or use apps that request social media access?',
    options:['Yes – Often','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Quizzes and personality apps harvest profile data. Avoid them or check permissions carefully.' },

  // CATEGORY I — Messaging & Social Engineering
  { id:'I1', cat:'I', text:'Do you click links received in direct messages from unknown senders?',
    options:['Yes – Often','Sometimes','Rarely','Never'],
    risk:   [1.0, 0.6, 0.2, 0.0],
    tip:'Never click DM links from unknown senders. Verify through official channels first.' },
  { id:'I2', cat:'I', text:'Have you ever received suspicious messages claiming to be from a company or friend?',
    options:['Yes – Responded','Yes – Ignored','No','Not Sure'],
    risk:   [1.0, 0.2, 0.0, 0.4],
    tip:'Verify unexpected messages through a separate channel before responding.' },
  { id:'I3', cat:'I', text:'Do you share sensitive information (passwords, OTPs, IDs) over DMs?',
    options:['Yes','Rarely','Never','Not Sure'],
    risk:   [1.0, 0.3, 0.0, 0.5],
    tip:'Never share credentials, OTPs, or government IDs over any messaging platform.' },
  { id:'I4', cat:'I', text:'Are your direct messages visible to people outside your connections?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [0.9, 0.0, 0.6, 0.7],
    tip:'Restrict DMs to followers/friends only in your messaging privacy settings.' },

  // CATEGORY J — Digital Footprint
  { id:'J1', cat:'J', text:'Have you ever searched for yourself online to check your digital footprint?',
    options:['Never','Once','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.6, 0.3, 0.0],
    tip:'Search your name + city regularly. Set up Google Alerts for your name.' },
  { id:'J2', cat:'J', text:'Is your social media profile indexed by search engines (appears in Google)?',
    options:['Yes','No','Not Sure','Never Checked'],
    risk:   [0.9, 0.0, 0.7, 0.7],
    tip:'Disable search engine indexing in Privacy Settings to reduce your public footprint.' },
  { id:'J3', cat:'J', text:'Have you ever deactivated or deleted old unused social media accounts?',
    options:['No – Have Many Old Accounts','Rarely','Sometimes','Yes – Regularly'],
    risk:   [1.0, 0.7, 0.3, 0.0],
    tip:'Delete inactive accounts. Each dormant account is a potential breach point.' },
  { id:'J4', cat:'J', text:'Do you know what data social media platforms collect about you?',
    options:['No Idea','Vague Idea','Somewhat','Yes – I\'ve Read Their Privacy Policy'],
    risk:   [1.0, 0.7, 0.4, 0.0],
    tip:'Read platform privacy policies and use "Download My Data" tools to audit what they store.' },
]

module.exports = { QUESTIONS, CATEGORIES }